### ISSUE TITLE
Read key:value pairs from metadata topic

### ISSUE THREAD

**Issue by cbandera** [swri-robotics/bag-database#43]
Hi,

would it by possible to add the functionality to read several key:value pairs from a specified topic?
I think of using a std::msgs/String message similar to the vehicle_name topic. But instead of providing just a single word, I would like to pass a whole dict of key:value pairs, possibly in yaml format:

``` yaml
General:
  CreatedBy: user
  Description: "A drive through the park"
Environment:
  Location: Some Park
  Weather: Sunny
Platform:
  VehicleName: ...
  Sensors: Cameras...
```

This schema could even be assumed fixed, through e.g. a config file. I don't have enough experience with java to be able to fully understand how the database is build up. Could someone give me an estimate of how complicated that would be? (e.g. is it possible with the way the DB is build up right now)

The advantage of having such a functionality is, that you could insert this metadata into the bagfile at record time (through additional tooling, like [rosbag_metadata](https://github.com/hordurk/rosbag_metadata)). Forcing the user to specify data at the time of recording, and placing the metadata in the same file as the recording itself has several advantages, e.g. (you could access this information directly from the console, you don't have to rely on people providing the metainformation afterwards, when uploading the file to the database...)
